spring.application.name=backend

# Server port for our REST API
server.port=8081

# MongoDB connection
spring.mongodb.uri=mongodb://localhost:27017/iot_platform

# MQTT broker connection (custom properties we'll read ourselves in code)
mqtt.broker.url=tcp://127.0.0.1:1883
mqtt.client.id=spring-boot-backend
mqtt.topic.filter=sensors/+/readings